import fs from 'node:fs';

// ─────────────────────────────────────────────────────────────────────────
// Stage 4 — Report
//
// Turns Stage 3's results (plus whatever Stage 0/1 understanding and
// authentication evidence is available) into CODESTRESS.md. Written in the
// same "state the evidence, mark what's unproven" tone as the rest of this
// project's reports (see stage1Understand.js's REPORT_SECTIONS and
// verifyAuthentication.js's outcome() detail strings).
// ─────────────────────────────────────────────────────────────────────────

function scoreLabel(score) {
  if (score >= 90) return 'Excellent';
  if (score >= 75) return 'Good';
  if (score >= 50) return 'Needs Attention';
  return 'Critical';
}

export function buildReport({ target, repo, authentication, understanding, results }) {
  const passed = results.filter(r => r.status === 'PASSED');
  const failed = results.filter(r => r.status === 'FAILED');
  const warned = results.filter(r => r.status === 'WARNING');
  const score = Math.max(0, Math.round(100 - failed.length * 12 - warned.length * 4));

  const lines = [];
  lines.push('# CodeStress Report');
  lines.push(`**Target:** ${target}`);
  if (repo) lines.push(`**Repo:** ${typeof repo === 'string' ? repo : repo.location}`);
  lines.push(`**Date:** ${new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC`);
  lines.push('**Engine:** IBM Bob 2.0');
  lines.push('\n---\n');

  lines.push('## App Summary');
  if (understanding?.aiUnderstanding) {
    lines.push(understanding.aiUnderstanding.slice(0, 1500));
  } else if (understanding?.routes) {
    lines.push(`Heuristic route scan only (no AI understanding available): ${understanding.endpointsCount ?? understanding.routes.length} endpoint(s) across ${understanding.routeGroupsCount ?? '?'} route group(s).`);
  } else {
    lines.push('No source understanding was available when this report was generated.');
  }
  lines.push('');

  lines.push('## Authentication Evidence');
  if (authentication) {
    lines.push(`- Status: **${authentication.status}**${authentication.type ? ` (${authentication.type})` : ''}`);
    lines.push(`- Detail: ${authentication.detail}`);
    if (authentication.evidence?.length) {
      for (const step of authentication.evidence) lines.push(`  - ${step.step}: ${step.endpoint} → HTTP ${step.httpStatus}`);
    }
  } else {
    lines.push('No authentication was attempted (public/unauthenticated run).');
  }
  lines.push('');

  lines.push('## Results');
  lines.push('| Tests | Passed | Failed | Warnings |');
  lines.push('|-------|--------|--------|----------|');
  lines.push(`| ${results.length} | ${passed.length} | ${failed.length} | ${warned.length} |`);
  lines.push('');
  lines.push(`**Security Score: ${score} / 100 — ${scoreLabel(score)}**`);
  lines.push('\n---\n');

  if (failed.length) {
    for (const f of failed) {
      lines.push(`## 🔴 CRITICAL — ${f.testType}`);
      lines.push(`- Endpoint : ${f.endpoint}`);
      if (f.file) lines.push(`- File     : ${f.file}${f.line ? `:${f.line}` : ''}`);
      if (f.payload) lines.push(`- Payload  : ${f.payload}`);
      lines.push(`- Result   : HTTP ${f.httpStatus} — ${f.evidence}`);
      lines.push(`- Fix      : ${f.fix}`);
      lines.push('');
    }
  } else {
    lines.push('## ✅ No critical failures found\n');
  }

  if (warned.length) {
    lines.push('---\n');
    for (const w of warned) {
      lines.push(`## 🟡 WARNING — ${w.testType}`);
      lines.push(`- Endpoint : ${w.endpoint}`);
      if (w.payload) lines.push(`- Payload  : ${w.payload}`);
      lines.push(`- Note     : ${w.note}`);
      lines.push('');
    }
  }

  lines.push('---\n');
  lines.push('## ✅ Passed Tests');
  if (passed.length) {
    for (const p of passed) lines.push(`- ${p.testType} on ${p.endpoint} ................. passed`);
  } else {
    lines.push('- (none)');
  }
  lines.push('');

  lines.push('---\n');
  lines.push('## Hardened Code');
  lines.push('Not yet generated. This requires the AI to rewrite the vulnerable file sections listed');
  lines.push('above under "Failures" — not implemented in this build. See each failure\'s File/Fix fields');
  lines.push('for where and what to change manually.');
  lines.push('');

  lines.push('---');
  lines.push('*Generated by CodeStress — Stress test your logic, not just your server.*');
  lines.push('*Heuristic detection: findings marked WARNING need human review before being treated as real vulnerabilities.*');

  return lines.join('\n');
}

export function writeReport(outPath, data) {
  const markdown = buildReport(data);
  fs.writeFileSync(outPath, markdown, 'utf8');
  return markdown;
}